(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["Ultraspherical`","RiemannHilbert`Common`"];
BandedOperator;
ReplaceEntry;
LeftBandwidth;
RightBandwidth;
IncreaseLength;
ApplyToRows;
LowerIndex;
LeftIndex;
RightIndex;
IncreaseSize;
GetFill;
SetFill;
GetRowGenerator;
GetFillValue;
Filler;
Givens;
GivensReduce;
Begin["Private`"];


GetFill[BandedOperator[A_List,jsh_,fill_List,rowgen_,___],i_]:=fill[[i]];
GetFillValue[BandedOperator[A_List,jsh_,fill_List,rowgen_],{i_,_}]:=fill[[i]];
GetFillValue[BandedOperator[A_List,jsh_,fill_List,rowgen_,Filler->fls_],{i_,j_}]:=fill[[i]].fls[j];
SetFill[BandedOperator[A_List,jsh_,fill_List,rowgen_,opts___],i_,val_]:=BandedOperator[A,jsh,ReplacePart[fill,i->val],rowgen,opts];
GetRowGenerator[BandedOperator[A_List,jsh_,fill_List,rowgen_,___]]:=rowgen;

BandedOperator/:bnd_BandedOperator[[i_Integer,j_Integer]]:=\[Piecewise]{
 {First[bnd][[i,j-LeftIndex[bnd,i]+1]], i<=Length[bnd]&&LeftIndex[bnd,i]<=j<=RightIndex[bnd,i]},
 {GetFillValue[bnd,{i,j}], i<=Length[bnd]&&j>RightIndex[bnd,i]},
 {GetRowGenerator[bnd][i][[j-LeftIndex[bnd,i]+1]], LeftIndex[bnd,i]<=j<=RightIndex[bnd,i]},
 {0, True}
};
BandedOperator/:bnd_BandedOperator[[i_List,j_Integer]]:=bnd[[#,j]]&/@i;
BandedOperator/:sp_BandedOperator[[i_Integer,jm_Integer;;jM_Integer]]:=Module[{j},
	Table[sp[[i,j]],{j,jm,jM}]];
BandedOperator/:sp_BandedOperator[[im_Integer;;iM_Integer,j_Integer]]:=Module[{i},
	Table[sp[[i,j]],{i,im,iM}]];
BandedOperator/:sp_BandedOperator[[im_Integer;;iM_Integer,jm_Integer;;jM_Integer]]:=Module[{i},
	Table[sp[[i,j]],{i,im,iM},{j,jm,jM}]];


LeftBandwidth[BandedOperator[A_List,jsh_,___]]:=1-jsh;
RightBandwidth[BandedOperator[A_List,jsh_,___]]:=Length[A[[1]]]-jsh;
LeftIndex[bnd_BandedOperator,row_]:=Max[row+LeftBandwidth[bnd],1];
RightIndex[bnd_BandedOperator,row_]:=LeftIndex[bnd,row]+\[Piecewise]{
 {Length[First[bnd][[row]]], row<=Length[bnd]},
 {Length[GetRowGenerator[bnd][row]], True}
}-1;

LowerIndex[bnd_BandedMatrix,col_]:=col-LeftBandwidth[bnd];

Bandwidth[bnd_BandedOperator]:=RightBandwidth[bnd]-LeftBandwidth[bnd]+1;

BandedOperator/:Length[BandedOperator[A_List,___]]:=Length[A];
BandedOperator/:Dimensions[BandedOperator[A_List,jsh_,___]]:={Length[A],Length[A[[-1]]]+Length[A]-jsh};

ToArray[bnd_BandedOperator]:=bnd[[;;Length[bnd],;;Dimensions[bnd][[2]]]];
BandedOperator/:MatrixForm[bnd_BandedOperator]:=MatrixMap[MatrixForm,bnd[[;;Length[bnd]+3,;;RightIndex[bnd,Length[bnd]]+3]]]//MatrixForm;


IncreaseLength[BandedOperator[A_List,jsh_,fill_List,rowgen_,opts___]]:=BandedOperator[Join[A,{rowgen[Length[A]+1]}],jsh,Append[fill,0 Last[fill]],rowgen,opts];



IncreaseRightIndex[bnd:BandedOperator[A_List,jsh_,fil_List,rowgen_,opts___],i_,j_]:=Module[{B},
If[j<=RightIndex[bnd,i],
bnd
,
B=A;
B[[i]]=Append[B[[i]],bnd[[i,RightIndex[bnd,i]+1]]];
IncreaseRightIndex[BandedOperator[B,jsh,fil,rowgen,opts],i,j]
]
];


ReplaceEntry[bnd:BandedOperator[A_List,jsh_,fil_List,rowgen_,fls:OptionsPattern[]],{i_,j_},p_,opts:OptionsPattern[IncreaseSize->False]]:=Module[{B,nfil},

If[j<LeftIndex[bnd,i],
Throw["left of left entry"]];

If[i>Length[A],
If[!OptionValue[IncreaseSize],
Throw["Replacing entry past size"]];
ReplaceEntry[bnd//IncreaseLength,{i,j},p,opts]
,
If[j<=RightIndex[bnd,i],
B=A;
B[[i,j-LeftIndex[bnd,i]+1]]=p;
BandedOperator[B,jsh,fil,rowgen,fls]
,
If[!OptionValue[IncreaseSize],
Throw["Replacing entry past size"]];

ReplaceEntry[IncreaseRightIndex[bnd,i,j],{i,j},p,opts]
]
]
];

ApplyToRows[G_,Bn_BandedOperator,{row1_,row2_}]:=Module[{vals,Bn1},
Bn1=Bn;

Do[
vals=G.Bn1[[{row1,row2},i]];
Bn1=ReplaceEntry[Bn1,{row1,i},vals[[1]],IncreaseSize->True];
Bn1=ReplaceEntry[Bn1,{row2,i},vals[[2]],IncreaseSize->True];

,{i,LeftIndex[Bn1,row2],RightIndex[Bn1,row2]}];


vals=G.{GetFill[Bn1,row1],GetFill[Bn1,row2]};

Bn1=SetFill[Bn1,row1,vals[[1]]];
Bn1=SetFill[Bn1,row2,vals[[2]]];

Bn1
];



BandedOperator/:c_?NumberQ BandedOperator[A_List,jsh_,fill_List,rowgen_]:=BandedOperator[c A,jsh,c fill, c rowgen[#]&]


ApplyToRows[G_,Bn_BandedOperator,Bnn_BandedOperator,{row1_,row2_}]:=Module[{vals,Bn1,Bn2,i},
Bn1=Bn;
Bn2=Bnn;

Do[
vals=G.{Bn1[[row1,i]],Bn2[[row2,i]]};
Bn1=ReplaceEntry[Bn1,{row1,i},vals[[1]],IncreaseSize->True];
Bn2=ReplaceEntry[Bn2,{row2,i},vals[[2]],IncreaseSize->True];

,{i,LeftIndex[Bn2,row2],RightIndex[Bn2,row2]}];


vals=G.{GetFill[Bn1,row1],GetFill[Bn2,row2]};
Bn1=SetFill[Bn1,row1,vals[[1]]];
Bn2=SetFill[Bn2,row2,vals[[2]]];

{Bn1,Bn2}
];

(*This is for operator of operators *)

ApplyToRows[G_,BDx_BandedOperator,{row1_,row2_},{srow1_,srow2_}]:=Module[{vals,Bn1,B1,B2,i},
Bn1=BDx;

Do[
{B1,B2}=Bn1[[{row1,row2},i]];
{B1,B2}=ApplyToRows[G,B1,B2,{srow1,srow2}];
Bn1=ReplaceEntry[Bn1,{row1,i},B1,IncreaseSize->True];
Bn1=ReplaceEntry[Bn1,{row2,i},B2,IncreaseSize->True];

,{i,LeftIndex[Bn1,row2],RightIndex[Bn1,row2]}];


{B1,B2}={GetFill[Bn1,row1],GetFill[Bn1,row2]};
{B1,B2}=ApplyToRows[G,#[[1]],#[[2]],{srow1,srow2}]&/@Thread[{B1,B2}]//Thread;

Bn1=SetFill[Bn1,row1,B1];
Bn1=SetFill[Bn1,row2,B2];

Bn1
];


ApplyToRows[G_,BDx_BandedOperator,Bd2_BandedOperator,{row1_,row2_},{srow1_,srow2_}]:=Module[{vals,Bn1,B1,B2,Bn2},
Bn1=BDx;
Bn2=Bd2;

Do[
{B1,B2}={Bn1[[row1,i]],Bn2[[row2,i]]};
{B1,B2}=ApplyToRows[G,B1,B2,{srow1,srow2}];
Bn1=ReplaceEntry[Bn1,{row1,i},B1,IncreaseSize->True];
Bn2=ReplaceEntry[Bn2,{row2,i},B2,IncreaseSize->True];

,{i,LeftIndex[Bn2,row2],RightIndex[Bn2,row2]}];


{B1,B2}={Bn1[[row1,RightIndex[Bn1,row2]+1]],Bn2[[row2,RightIndex[Bn1,row2]+1]]};
{B1,B2}=ApplyToRows[G,B1,B2,{srow1,srow2}];

Bn1=SetFill[Bn1,row1,B1];
Bn2=SetFill[Bn2,row2,B2];

{Bn1,Bn2}
];

(*This is for list operators of operators *)

ApplyToRows[G_,BL:{__BandedOperator},{row1_,row2_},{srow1_,srow2_},{ssrow1_,ssrow2_}]:=Module[{vals,Bn1,B1,B2},
Bn1=BL;


{B1,B2}=Bn1[[{row1,row2}]];
{B1,B2}=ApplyToRows[G,B1,B2,{srow1,srow2},{ssrow1,ssrow2}];
Bn1[[row1]]=B1;
Bn1[[row2]]=B2;

Bn1
];



Givens[Bin_,Binn_,{i_,j_},k_]:=Module[{A,a,bB},
a=Bin[[i,k]];
bB=Binn[[j,k]];
({
 {a, bB},
 {-bB, a}
})/Norm[{a,bB}]
];
GivensReduce[BDx_,{row1_,row2_}]:=Module[{G},
G=Givens[BDx,BDx,{row1,row2},row1]//N;
ApplyToRows[G,BDx,{row1,row2}]
];
GivensReduce[BDx_,{row1_,row2_},{srow1_,srow2_}]:=Module[{G},
G=Givens[BDx[[row1,row1]],BDx[[row2,row1]],{srow1,srow2},srow1]//N;
ApplyToRows[G,BDx,{row1,row2},{srow1,srow2}]
];
GivensReduce[BDx_,{row1_,row2_},{srow1_,srow2_},{ssrow1_,ssrow2_}]:=Module[{G},
G=Givens[BDx[[row1]][[srow1,srow1]],BDx[[row2]][[srow2,srow1]],{ssrow1,ssrow2},ssrow1]//N;
ApplyToRows[G,BDx,{row1,row2},{srow1,srow2},{ssrow1,ssrow2}]
]


End[];
EndPackage[];
